/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: shyam11 (https://sketchfab.com/shyam11)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/google-logo-a08a013b2aa747bb923863c6ae15e6be
title: Google Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.lambert3.geometry} material={materials.lambert3} />
          <mesh geometry={nodes.lambert2.geometry} material={materials.lambert2} />
          <group position={[-10.06, -11.06, -11.78]} scale={[1, 1, 1.24]}>
            <mesh geometry={nodes.lambert4.geometry} material={materials.lambert4} />
            <mesh geometry={nodes.lambert5.geometry} material={materials.lambert5} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
