/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mounirchikhtouhami (https://sketchfab.com/mounirchikhtouhami)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rocket-5f62bdd53cb542669372e036c5bcc114
title: Rocket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {a} from '@react-spring/three'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.01, 0.05, -0.01]}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
            <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
          </group>
          <group position={[0, 2.2, 0.01]} scale={0.48}>
            <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
          </group>
          <group position={[0.01, 0.74, 0.4]} rotation={[1.52, 0, 0]} scale={1.1}>
            <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.glass} />
          </group>
          <group position={[0, -1.45, 0]}>
            <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
          </group>
          <group position={[-0.52, -1.35, 0]} rotation={[0, 0, 0.51]} scale={[0.15, 0.28, 0.08]}>
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
          </group>
          <group position={[0, -1.35, 0.52]} rotation={[0.51, Math.PI / 2, 0]} scale={[0.15, 0.28, 0.08]}>
            <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
          </group>
          <group position={[0.52, -1.35, 0]} rotation={[-Math.PI, 0, -2.63]}>
            <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
          </group>
          <group position={[0, -1.35, -0.52]} rotation={[-0.51, -Math.PI / 2, 0]} scale={[0.15, 0.28, 0.08]}>
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
